// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6cPFREz-l3YOuXTwjEs8C8qzrlpf_biI',
    appId: '1:781824381029:web:488564d138a9159738b68c',
    messagingSenderId: '781824381029',
    projectId: 'assignment-98d47',
    authDomain: 'assignment-98d47.firebaseapp.com',
    storageBucket: 'assignment-98d47.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZHhRk42I6Kbad-VfTDu7b4QpHybeKFGo',
    appId: '1:781824381029:android:e1978a23cd5c19e238b68c',
    messagingSenderId: '781824381029',
    projectId: 'assignment-98d47',
    storageBucket: 'assignment-98d47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYeqhvHZUU5mwr02EP34ag9MxqP8dDhPc',
    appId: '1:781824381029:ios:6b7df4c0893d0f2438b68c',
    messagingSenderId: '781824381029',
    projectId: 'assignment-98d47',
    storageBucket: 'assignment-98d47.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYeqhvHZUU5mwr02EP34ag9MxqP8dDhPc',
    appId: '1:781824381029:ios:845153e9f6f99e1838b68c',
    messagingSenderId: '781824381029',
    projectId: 'assignment-98d47',
    storageBucket: 'assignment-98d47.appspot.com',
    iosBundleId: 'com.example.firebaseProject.RunnerTests',
  );
}
